#!/bin/bash
NUM_FILES=$( find $( pwd ) -name "*.pid" | wc -l )

if [ ${NUM_FILES} -ne 0 ]
then
    PID_FILES=$( find $( pwd ) -name "*.pid" )
    for PID_FILE in ${PID_FILES}
    do   
        PROCESS_ID=$( cat ${PID_FILE} )
        kill ${PROCESS_ID}
        echo "Successfully kill process_id: ${PROCESS_ID} from ${PID_FILE}"
    done
else
    echo -e "Can't find any file with pid extenstion\n"
fi

# If it add argument '--reset-env', it will delete all files which are generated by Airflow.
# You also can use airflow resetdb to reset env.
if [ "$1" == "--reset-env" ]
then
    sleep 1
    echo -e "Remove all files which are generated by Airflow...\n"
    . "./reset-env.sh" --source-only
    reset_env
fi

# Reference:
# How to kill Airflow Webserver and Scheduler
# https://stackoverflow.com/questions/65656254/how-to-kill-airflow-scheduler-and-webserver
